#================ Porta do servidor HTTP do Quarkus ==================
quarkus.http.host=0.0.0.0
quarkus.http.port=8081

#========================= Keycloak / OIDC ===========================
# Configurações para o auth-service se comunicar com o Keycloak e validar tokens
quarkus.oidc.auth-server-url=http://localhost:8080/realms/keycloak-auth-service-realm
quarkus.oidc.client-id=${KC_CLIENT_ID}
quarkus.oidc.credentials.secret=${KC_CLIENT_SECRET}

# auth-service atua como web-app (faz login) não apenas valida tokens
quarkus.oidc.application-type=web-app

# Para o auth-service chamar o Keycloak via REST (token endpoint)
quarkus.keycloak.devservices.enabled=false

# Keycloak config
keycloak.realm=keycloak-auth-service-realm
keycloak.client-id=${KC_CLIENT_ID}
keycloak.client-secret=${KC_CLIENT_SECRET}

# REST Client: URL base do Keycloak para o KeycloakTokenClient (configKey = "keycloak")
quarkus.rest-client.keycloak.url=http://localhost:8080

# OIDC (validação de tokens recebidos ? por ora desabilitado no auth-service)
quarkus.oidc.enabled=false

# Log
quarkus.log.level=INFO
quarkus.log.category."io.github.brunofelix".level=DEBUG
