# Perfil dev para Quarkus
# Use ./mvnw quarkus:dev -Dquarkus.profile=dev

quarkus.http.host=0.0.0.0
quarkus.http.port=8081

quarkus.oidc.auth-server-url=http://localhost:8080/realms/keycloak-auth-service-realm
quarkus.oidc.client-id=${KC_CLIENT_ID:keycloak-auth-service}
quarkus.oidc.credentials.secret=${KC_CLIENT_SECRET:OFQGcGgM3iJrpQHFOphVcD5wCF8SblPJ}
quarkus.oidc.application-type=web-app

quarkus.keycloak.devservices.enabled=false

keycloak.realm=keycloak-auth-service-realm
keycloak.client-id=${KC_CLIENT_ID:keycloak-auth-service}
keycloak.client-secret=${KC_CLIENT_SECRET:OFQGcGgM3iJrpQHFOphVcD5wCF8SblPJ}

quarkus.rest-client.keycloak.url=http://localhost:8080

quarkus.oidc.enabled=false

quarkus.log.level=INFO
quarkus.log.category."io.github.brunofelix".level=DEBUG
