# Garante que o Quarkus aceite conexões externas no container do Codespaces
quarkus.http.host=0.0.0.0
quarkus.http.port=8081


# Configuração de Logs com SLF4J (Padrão Quarkus) - Formato: 14:30:05 INFO  [or.ac.Gr] (executor-thread-1) Mensagem de log aqui
# quarkus.log.console.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n